### ISSUE TITLE
Issue with the calculation and offer of cooperation 

### ISSUE THREAD

**Issue by pbedyn** [JEK58/wprs-forecast#1]
Hello Stephan,
I have a code in Python that does the same thing and I noticed that your code underestimates the competition score. I was also thinking that perhaps you would like to join forces and do this project together? I would love to help.
If you’re interested please contact me at pawel.bedynski@gmail.com.

Kind regards,
Pawel

**Comment by pbedyn** [comment]
Hi Stephan,
Im wondering if you’d be open to adding a feature to your program that
would calculate potential points and confirmed points. As I understand it
currently only calculates the latter but the potential points based on all
pilots who have not yet confirmed is an important piece of information.
Just for your consideration.

Kind regards,
Pawel

**Comment by JEK58** [comment]
Hey Pawel,

I added this feature a few days ago:

<img width="515" alt="Screenshot 2023-05-03 at 16 20 36" src="https://user-images.githubusercontent.com/35194489/235944344-6ebac449-3557-4b67-8a87-c71a64a27100.png">

**Comment by pbedyn** [comment]
Nice! All the best!

Kind regards,
Pawel
