### ISSUE TITLE
Asia tour doesn't show name

### ISSUE THREAD

**Issue by hyperknot** [JEK58/WPRS-Forecast#34]
https://wprs-forecast.org/forecast?url=https://pwca.events/pwca-asian-tour-india-bir-2024/

**Comment by JEK58** [comment]
Thanks for reporting. The PWC changed its layout for next year and I already adapted to that. (I scrape the events page) Maybe I'll try to find a smart way to scrape both formats but as it's only for one event I might not do it;)

**Comment by hyperknot** [comment]
If it's only for one event than I agree it makes no sense :-)
