### ISSUE TITLE
Historical results are totally different, divided by 3?

### ISSUE THREAD

**Issue by hyperknot** [JEK58/WPRS-Forecast#35]
Did CIVL just divide all values by 3 recently?

The History page is off because of this, but everything on CIVL is also totally different compared to how it used to be.

https://wprs-forecast.org/history

**Comment by JEK58** [comment]
I'm not aware of a change in the WPRS system. Let's see if it gets fixed on Monday.

**Comment by hyperknot** [comment]
CIVL believes it's a bug.

**Comment by JEK58** [comment]
Thanks for letting me know!
